### ISSUE TITLE
Add healthcheck to dockerfile

### ISSUE THREAD

**Issue by normanrz** [scalableminds/fossildb#29]
The server dockerfile doesn't have a healthcheck yet. Using the healthcheck from the client is not possible because it is in a different image. Possible options that I see:
- Make a big docker image that has both client and server in one
- Hack a health check with [grpcurl](https://github.com/fullstorydev/grpcurl)

**Comment by normanrz** [comment]
@jstriebel @fm3 what do you think?

**Comment by jstriebel** [comment]
Couldn't we simply add a HTTP route? Alternatively I would propose to directly exec something like you proposed, but then rather use [`grpc-health-probe`](https://github.com/grpc-ecosystem/grpc-health-probe/). We could also run a [sidecar container](https://github.com/otsimo/grpc-health), but that seems too weird to me.

**Comment by normanrz** [comment]
I don't think sidecars are an option in a docker-only (no k8s) world.
